# Generated by Django 4.0 on 2023-02-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('time_opened', models.CharField(blank=True, default=datetime.datetime.now, max_length=1000)),
                ('time_closed', models.CharField(blank=True, default='', max_length=1000)),
                ('diff', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('time_opened', models.DateTimeField(auto_now_add=True)),
                ('time_closed', models.CharField(blank=True, default='', max_length=1000)),
                ('diff', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
